const P = { eye: "M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8zM12 15a3 3 0 100-6 3 3 0 000 6z", tasks: "M9 11l3 3L22 4M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11", cal: "M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 012 2v14a2 2 0 01-2 2H5a2 2 0 01-2-2V6a2 2 0 012-2z", done: "M22 11.08V12a10 10 0 11-5.93-9.14M22 4L12 14.01l-3-3", folder: "M20 20a2 2 0 002-2V8a2 2 0 00-2-2h-7.9a2 2 0 01-1.69-.9L9.6 3.9A2 2 0 007.93 3H4a2 2 0 00-2 2v13a2 2 0 002 2z", users: "M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2M9 11a4 4 0 100-8 4 4 0 000 8M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75", share: "M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8M16 6l-4-4-4 4M12 2v13", set: "M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6", search: "M11 19a8 8 0 100-16 8 8 0 000 16zM21 21l-4.35-4.35", bell: "M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9M13.73 21a2 2 0 01-3.46 0", plus: "M12 5v14M5 12h14", mail: "M4 4h16a2 2 0 012 2v12a2 2 0 01-2 2H4a2 2 0 01-2-2V6a2 2 0 012-2zM22 6l-10 7L2 6", chart: "M18 20V10M12 20V4M6 20v-6", dots: "M12 12h.01M19 12h.01M5 12h.01", x: "M18 6L6 18M6 6l12 12", check: "M20 6L9 17l-5-5", clock: "M12 22a10 10 0 100-20 10 10 0 000 20zM12 6v6l4 2", briefcase: "M20 7H4a2 2 0 00-2 2v10a2 2 0 002 2h16a2 2 0 002-2V9a2 2 0 00-2-2zM16 21V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v16", user: "M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2M12 11a4 4 0 100-8 4 4 0 000 8", book: "M4 19.5A2.5 2.5 0 016.5 17H20V2H6.5A2.5 2.5 0 004 4.5zM20 22H6.5A2.5 2.5 0 014 19.5", rocket: "M12 15l-3-3a22 22 0 012-3.95A12.9 12.9 0 0122 2c0 2.7-.8 7.5-6 11a22 22 0 01-4 2zM9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5", heart: "M20.8 4.6a5.5 5.5 0 00-7.8 0L12 5.7l-1-1.1a5.5 5.5 0 00-7.8 7.8l1 1.1L12 21l7.8-7.5 1-1.1a5.5 5.5 0 000-7.8z", trash: "M3 6h18M19 6l-1 14H6L5 6M10 11v6M14 11v6M9 6V4h6v2", edit: "M12 20h9M16.5 3.5a2.1 2.1 0 013 3L7 19l-4 1 1-4z", undo: "M3 7v6h6M3 13a9 9 0 105.7-8.5" };
        const I = (n, s = 18, w = 2) => `<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round"><path d="${P[n]}"/></svg>`;
        const $ = s => document.querySelector(s);
        const pad = n => String(n).padStart(2, '0');
        const iso = d => d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate());
        const off = n => { const d = new Date(); d.setDate(d.getDate() + n); return iso(d) };
        const TODAY = off(0);
        const fmt = (s, o = { month: 'short', day: 'numeric' }) => new Date(s + 'T00:00').toLocaleDateString('en-US', o);
        const demoTeam = [{ id: 'sam', n: 'Sam Rivera', c: '#e5484d' }, { id: 'priya', n: 'Priya Nair', c: '#30a46c' }, { id: 'jo', n: 'Jo Kim', c: '#f5a524' }]; const team = [{ id: 'me', n: 'You', c: '#5b5bd6' }];
        const ini = id => { const m = team.find(t => t.id === id) || demoTeam.find(t => t.id === id) || team[0]; return `<span class="av" title="${m.n}" style="background:${m.c};width:24px;height:24px;font-size:10px">${m.n.split(' ').map(x => x[0]).join('')}</span>` };
        const COL = ['#5b5bd6', '#0091ff', '#30a46c', '#f5a524', '#e5484d', '#8e4ec6'];
        const ICONS = ['briefcase', 'user', 'book', 'rocket', 'heart', 'folder'];
        let n = 0; const mk = (t, d, o, tm, p, c, done = 0, who = 'me', st = 'To do') => ({ id: 't' + (++n), t, d, date: off(o), time: tm, p, c, done: !!done, doneOn: done ? off(-done + 1) : null, who, st, rem: '30 min before', cm: [] });
        const demo = {
            tasks: [mk('Finalize Q4 roadmap deck', 'Review slides with product leads', 0, '10:30', 'High', 'work'), mk('Team standup notes', 'Summarize blockers for the week', 0, '09:15', 'Medium', 'work', 0, 'sam', 'In progress'), mk('Morning run — 5 km', 'Riverside loop before breakfast', 0, '06:30', 'Low', 'health', 1), mk('Read chapter 7: Algorithms', 'Take notes on graph traversal', 0, '19:00', 'Medium', 'study'), mk('Book dentist appointment', 'Call the clinic before noon', 0, '12:00', 'Low', 'personal'), mk('Design system audit', 'Check spacing tokens across screens', 1, '14:00', 'High', 'projects', 0, 'priya', 'In progress'), mk('Submit expense report', 'Attach receipts from the trip', 2, '17:00', 'Medium', 'work'), mk('Study group session', 'Prepare practice questions', 3, '16:00', 'Medium', 'study', 0, 'jo'), mk('Grocery shopping', 'Weekly essentials', 4, '18:30', 'Low', 'personal'), mk('Plan sprint retrospective', 'Draft agenda and format', 8, '11:00', 'Medium', 'projects', 0, 'sam'), mk('Renew gym membership', 'Compare annual plans', 12, '10:00', 'Low', 'health'), mk('Launch beta website', 'Final QA and deploy', 25, '09:00', 'High', 'projects'), mk('Overdue: send invoice', 'Client is waiting', -2, '15:00', 'High', 'work'), mk('Prepare weekly report', 'Metrics and highlights', -1, '16:00', 'Medium', 'work', 1), mk('Meditate 10 minutes', 'Breathing exercises', -2, '07:00', 'Low', 'health', 2), mk('Finish lab assignment', 'Submit on portal', -3, '23:00', 'High', 'study', 3), mk('Call mom', 'Catch up', -4, '20:00', 'Low', 'personal', 4)],
            cats: [{ id: 'work', n: 'Work', c: 0, i: 'briefcase' }, { id: 'personal', n: 'Personal', c: 1, i: 'user' }, { id: 'study', n: 'Study', c: 2, i: 'book' }, { id: 'projects', n: 'Projects', c: 5, i: 'rocket' }, { id: 'health', n: 'Health', c: 4, i: 'heart' }],
            mail: [{ id: 1, k: 'Invitation', f: 'Sam Rivera', s: 'Invited you to "Design Sprint" workspace', t: '9:41 AM', u: 1 }, { id: 2, k: 'Assigned', f: 'Priya Nair', s: 'Assigned you: Design system audit', t: '8:15 AM', u: 1 }, { id: 3, k: 'Reminder', f: 'Taskly', s: 'Finalize Q4 roadmap deck is due at 10:30 AM', t: 'Yesterday', u: 0 }, { id: 4, k: 'Update', f: 'Jo Kim', s: 'Commented on Study group session: "Bringing snacks!"', t: 'Yesterday', u: 1 }, { id: 5, k: 'Update', f: 'Sam Rivera', s: 'Marked Team standup notes as In progress', t: 'Mon', u: 0 }],
            theme: 'auto', notif: { email: true, push: true, digest: false }, weekStart: 'Mon', share: true, name: 'Alex Morgan'
        };
        let S = { page: 'tasks', filter: 'all', q: '', sort: 'date', cal: 'month', calDate: TODAY, catSel: null, menu: null, modal: null, ren: null, open: null, user: null, auth: 'login', busy: false, err: {}, f: {}, pm: false, conf: false, theme: 'light' };
        let saveTimer = null, saveQueue = Promise.resolve();
        const api = async (path, options = {}) => { const response = await fetch(path, { credentials: 'same-origin', ...options, headers: { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...options.headers } }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) { const error = new Error(body?.error || 'The request could not be completed.'); error.field = body?.field; throw error } return body };
        function enter(user, data) { Object.assign(S, { user: user.email, name: user.name, tasks: [], cats: demo.cats.map(c => ({ ...c })), mail: [], theme: 'light', page: 'tasks', filter: 'all', q: '', err: {}, f: {}, pwv: '', cfv: '', conf: false, editn: false, catSel: null }, data || {}); team[0].n = S.name }
        const persistNow = () => { clearTimeout(saveTimer); saveTimer = null; if (!S.user) return Promise.resolve(); const body = JSON.stringify({ tasks: S.tasks, cats: S.cats, mail: S.mail, theme: S.theme, name: S.name }); saveQueue = saveQueue.catch(() => { }).then(() => api('/api/data', { method: 'PUT', body })).catch(error => toast(error.message || 'Changes could not be saved.')); return saveQueue };
        const save = () => { if (!S.user) return; clearTimeout(saveTimer); saveTimer = setTimeout(persistNow, 250) };
        function start(user, data) { enter(user, data); toast('Welcome, ' + S.name.split(' ')[0] + '!') }
        const cat = id => S.cats.find(c => c.id === id) || { n: 'Uncategorized', c: 0, i: 'folder' };
        const toast = m => { const e = document.createElement('div'); e.className = 'toast'; e.textContent = m; document.body.appendChild(e); setTimeout(() => e.remove(), 2200) };
        const pw = { High: 0, Medium: 1, Low: 2 };
        const nav = [['tasks', 'My Tasks', 'tasks'], ['upcoming', 'Upcoming', 'cal'], ['completed', 'Completed', 'done'], 'Workspace', ['categories', 'Categories', 'folder'], ['collab', 'Collaborate', 'users'], ['shared', 'Shared Tasks', 'share']];
        const matches = t => { const q = S.q.toLowerCase(); return !q || t.t.toLowerCase().includes(q) || (t.d || '').toLowerCase().includes(q) || cat(t.c).n.toLowerCase().includes(q) || t.date.includes(q) || fmt(t.date).toLowerCase().includes(q) };
        function card(t, showDate) {
            const c = cat(t.c), col = COL[c.c];
            return `<div class="card task ${t.done ? 'done' : ''}"><button class="cb" data-a="toggle" data-id="${t.id}" aria-label="Complete">${t.done ? I('check', 14, 3) : ''}</button>
<div style="flex:1;min-width:0"><div class="tt">${t.t}</div><div class="ds">${t.d}</div>
<div class="meta"><span style="display:flex;gap:4px;align-items:center">${I('clock', 13)}${showDate ? fmt(t.date) + ' · ' : ''}${t.time}</span><span class="pr ${t.p}">${t.p}</span><span class="tag" style="background:${col}22;color:${col}">${c.n}</span>${t.who !== 'me' ? ini(t.who) : ''}</div></div>
<button class="ib" data-a="menu" data-id="${t.id}" aria-label="Menu">${I('dots', 18, 3)}</button>
${S.menu === t.id ? `<div class="menu"><button data-a="edit" data-id="${t.id}">Edit</button><button data-a="del" data-id="${t.id}" style="color:#e5484d">Delete</button></div>` : ''}</div>`
        }
        const head = (h, s, btn = true) => `<div class="top"><div><div class="date">${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</div><h1>${h}</h1><div class="sub">${s}</div></div>${btn ? `<button class="btn" data-a="add">${I('plus', 16, 2.5)}Add Task</button>` : ''}</div>`;
        const empty = m => `<div class="card empty">${I('done', 32)}<p>${m}</p></div>`;
        const pages = {
            tasks() {
                const all = S.tasks.filter(matches), td = all.filter(t => t.date === TODAY); const ts = S.tasks.filter(t => t.date === TODAY), dn = ts.filter(t => t.done).length, pc = ts.length ? Math.round(dn / ts.length * 100) : 0;
                let l = S.filter === 'completed' ? all.filter(t => t.done) : S.filter === 'high' ? all.filter(t => t.p === 'High' && !t.done) : S.filter === 'today' ? td : all.filter(t => !t.done);
                l = [...l].sort((a, b) => a.done - b.done || a.time.localeCompare(b.time));
                if (!S.tasks.length) return head(greet(), 'Your day is a blank canvas.') + firstRun(); return head(greet(), 'Stay organized and get things done.') + `<div class="card prog"><div style="font-size:28px;font-weight:700;color:var(--ac)">${pc}%</div><div style="flex:1"><div style="font-weight:600;margin-bottom:6px">${dn} of ${ts.length} tasks completed today</div><div class="bar"><i style="width:${pc}%"></i></div></div></div>
<div class="chips">${[['all', 'All'], ['today', 'Today'], ['high', 'High Priority'], ['completed', 'Completed']].map(([k, v]) => `<button class="chip ${S.filter === k ? 'on' : ''}" data-a="filter" data-id="${k}">${v}</button>`).join('')}</div>
${sections(l)}`
            },
            upcoming() {
                const f = S.tasks.filter(t => !t.done && t.date > TODAY && matches(t)); const srt = (a, b) => S.sort === 'priority' ? pw[a.p] - pw[b.p] : S.sort === 'category' ? cat(a.c).n.localeCompare(cat(b.c).n) : a.date.localeCompare(b.date);
                const g = { Tomorrow: [], 'This Week': [], 'Next Week': [], Later: [] }; f.forEach(t => { const d = (new Date(t.date) - new Date(TODAY)) / 864e5; (d <= 1 ? g.Tomorrow : d <= 7 ? g['This Week'] : d <= 14 ? g['Next Week'] : g.Later).push(t) });
                return head('Upcoming', 'Plan what comes next.') + `<div class="chips">${['date', 'priority', 'category'].map(k => `<button class="chip ${S.sort === k ? 'on' : ''}" data-a="sort" data-id="${k}">Sort: ${k}</button>`).join('')}</div>` + Object.entries(g).map(([k, v]) => v.length ? `<h3>${k} · ${v.length}</h3>` + v.sort(srt).map(t => card(t, true)).join('') : '').join('') || empty('Nothing upcoming.')
            },
            completed() {
                const l = S.tasks.filter(t => t.done && matches(t)).sort((a, b) => (b.doneOn || '').localeCompare(a.doneOn || '')); const wk = l.filter(t => t.doneOn >= off(-6)).length;
                return head('Completed', 'A record of everything you finished.', false) + `<div class="grid" style="margin-bottom:8px"><div class="card stat"><b>${l.length}</b><span>Total completed</span></div><div class="card stat"><b>${wk}</b><span>This week</span></div></div><h3>History</h3>` + (l.map(t => { const c = cat(t.c), col = COL[c.c]; return `<div class="card task"><span style="color:#30a46c">${I('done', 22)}</span><div style="flex:1"><div class="tt">${t.t}</div><div class="meta">Completed ${t.doneOn ? fmt(t.doneOn) : '—'}<span class="tag" style="background:${col}22;color:${col}">${c.n}</span></div></div><button class="btn g" data-a="toggle" data-id="${t.id}">${I('undo', 14)}<span class="hide-m">Restore</span></button><button class="ib" data-a="del" data-id="${t.id}" aria-label="Delete forever" style="color:#e5484d">${I('trash', 17)}</button></div>` }).join('') || empty('No completed tasks yet.'))
            },
            categories() { const sel = S.catSel; return head('Categories', 'Group tasks by what matters.', false) + `<div class="row" style="margin-bottom:16px"><input class="in" id="newcat" placeholder="New category name…"><button class="btn" data-a="addcat" style="flex:none">${I('plus', 16)}Create</button></div><div class="grid">${S.cats.map(c => { const k = S.tasks.filter(t => t.c === c.id).length, col = COL[c.c]; return `<div class="card stat" style="cursor:pointer;border-color:${sel === c.id ? col : ''}" data-a="selcat" data-id="${c.id}"><div style="display:flex;justify-content:space-between;align-items:center"><span style="width:38px;height:38px;border-radius:11px;background:${col}22;color:${col};display:grid;place-items:center">${I(c.i, 20)}</span><span><button class="ib" data-a="ren" data-id="${c.id}" style="width:28px;height:28px">${I('edit', 14)}</button><button class="ib" data-a="delcat" data-id="${c.id}" style="width:28px;height:28px">${I('trash', 14)}</button></span></div>${S.ren === c.id ? `<input class="in" id="rn" value="${c.n}" style="margin-top:10px" onclick="event.stopPropagation()">` : `<div style="font-weight:600;margin-top:10px">${c.n}</div>`}<span>${k} tasks</span></div>` }).join('')}</div>` + (sel ? `<h3>${cat(sel).n} tasks</h3>` + (S.tasks.filter(t => t.c === sel).map(t => card(t, true)).join('') || empty('No tasks in this category.')) : '') },
            collab() { const ts = S.tasks.filter(t => !t.done && t.who !== 'me' || S.open && t.id === S.open); return sharedView('Collaborate', 'Work together, stay in sync.', true) },
            shared() { return sharedView('Shared Tasks', 'Tasks shared with you and by you.', false) },
            calendar() {
                const d = new Date(S.calDate + 'T00:00'), y = d.getFullYear(), m = d.getMonth(); const sh = n => { const x = new Date(d); x.setDate(x.getDate() + n); S.calDate = iso(x) };
                let cells = []; if (S.cal === 'month') { const st = new Date(y, m, 1); st.setDate(1 - ((st.getDay() + 6) % 7)); for (let i = 0; i < 42; i++) { const x = new Date(st); x.setDate(st.getDate() + i); cells.push(x) } }
                else if (S.cal === 'week') { const st = new Date(d); st.setDate(d.getDate() - ((d.getDay() + 6) % 7)); for (let i = 0; i < 7; i++) { const x = new Date(st); x.setDate(st.getDate() + i); cells.push(x) } }
                const ag = S.tasks.filter(t => t.date === S.calDate).sort((a, b) => a.time.localeCompare(b.time));
                return head('Calendar', 'Tasks by day, week and month.', false) + `<div class="top" style="margin-bottom:12px"><div class="chips" style="margin:0">${['month', 'week', 'day'].map(k => `<button class="chip ${S.cal === k ? 'on' : ''}" data-a="calmode" data-id="${k}">${k[0].toUpperCase() + k.slice(1)}</button>`).join('')}</div><div style="display:flex;gap:6px;align-items:center"><button class="btn g" data-a="calnav" data-id="-1">‹</button><b style="min-width:130px;text-align:center">${d.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</b><button class="btn g" data-a="calnav" data-id="1">›</button></div></div>` + (S.cal === 'day' ? '' : `<div class="cal">${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(x => `<div class="h">${x}</div>`).join('')}${cells.map(x => { const k = iso(x), ts = S.tasks.filter(t => t.date === k); return `<button class="day ${k === S.calDate ? 'sel' : ''} ${k === TODAY ? 'td' : ''} ${S.cal === 'month' && x.getMonth() !== m ? 'dim' : ''}" data-a="calsel" data-id="${k}" style="${S.cal === 'week' ? 'min-height:120px' : ''}"><b style="font-size:12px">${x.getDate()}</b><div>${ts.slice(0, S.cal === 'week' ? 6 : 8).map(t => `<span class="dot" style="background:${COL[cat(t.c).c]}"></span>`).join('')}</div></button>` }).join('')}</div>`) + `<div class="top" style="margin-top:22px"><h3 style="margin:0">Agenda · ${fmt(S.calDate, { weekday: 'long', month: 'short', day: 'numeric' })}</h3><button class="btn g" data-a="add" data-id="${S.calDate}">${I('plus', 14)}Add on this day</button></div>` + (ag.map(t => card(t)).join('') || empty('Nothing scheduled.'))
            },
            analysis() {
                const T = S.tasks, dn = T.filter(t => t.done).length, ov = T.filter(t => !t.done && t.date < TODAY).length, pd = T.length - dn; const days = [...Array(7)].map((_, i) => { const k = off(i - 6); return { k, v: T.filter(t => t.doneOn === k).length } }), mx = Math.max(1, ...days.map(x => x.v));
                const ts = T.filter(t => t.date === TODAY), rate = ts.length ? Math.round(ts.filter(t => t.done).length / ts.length * 100) : 0;
                return head('Analysis', 'Simple insights into your productivity.', false) + `<div class="grid">${[['Total tasks', T.length, 'var(--tx)'], ['Completed', dn, '#30a46c'], ['Pending', pd, 'var(--ac)'], ['Overdue', ov, '#e5484d'], ['Today\'s completion', rate + '%', 'var(--ac)']].map(([a, b, c]) => `<div class="card stat"><b style="color:${c}">${b}</b><span>${a}</span></div>`).join('')}</div>
<h3>Weekly productivity</h3><div class="card" style="padding:20px;display:flex;align-items:flex-end;gap:12px;height:190px">${days.map(x => `<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:6px;height:100%;justify-content:flex-end"><span style="font-size:12px;color:var(--mu)">${x.v}</span><div style="width:100%;max-width:38px;border-radius:8px 8px 3px 3px;background:var(--ac);opacity:${x.v ? 1 : .2};height:${Math.max(4, x.v / mx * 100)}px;transition:height .5s"></div><span style="font-size:11px;color:var(--mu)">${fmt(x.k, { weekday: 'short' })}</span></div>`).join('')}</div>
<h3>By category</h3><div class="card" style="padding:18px">${S.cats.map(c => { const k = T.filter(t => t.c === c.id).length, col = COL[c.c]; return `<div style="display:flex;align-items:center;gap:12px;margin:8px 0"><span style="width:90px;font-weight:500">${c.n}</span><div class="bar"><i style="width:${k / Math.max(1, T.length) * 100}%;background:${col}"></i></div><span style="width:24px;text-align:right;color:var(--mu)">${k}</span></div>` }).join('')}</div>`
            },
            mail() { if (!S.mail.length) return head('Mail', 'Invitations, updates and reminders.', false) + empty('No messages yet. Invitations and task updates will appear here once collaboration is connected to a backend.'); return head('Mail', 'Invitations, updates and reminders.', false) + `<div class="card">${S.mail.map(m => `<button class="mail" data-a="read" data-id="${m.id}">${m.u ? '<i class="ud"></i>' : '<i style="width:8px;flex:none"></i>'}<div style="flex:1;min-width:0"><div style="display:flex;justify-content:space-between;gap:8px"><b style="font-weight:${m.u ? 700 : 500}">${m.f} · <span class="tag" style="background:var(--acs);color:var(--ac)">${m.k}</span></b><span style="color:var(--mu);font-size:12px;white-space:nowrap">${m.t}</span></div><div class="ds" style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${m.s}</div></div></button>`).join('')}</div>` },
            profile() {
                const b = (k) => `<button class="chip ${S.theme === k ? 'on' : ''}" data-a="theme" data-id="${k}">${k === 'light' ? '☀ Light' : '☾ Dark'}</button>`;
                return head('Settings', 'Manage your account and appearance.', false) + `<div class="card" style="padding:20px;display:flex;gap:16px;align-items:center;flex-wrap:wrap"><span class="av" style="background:var(--ac);width:64px;height:64px;font-size:22px">${ini2()}</span><div style="flex:1;min-width:160px"><div style="font-size:18px;font-weight:700">${S.name}</div><div class="sub">${S.user}</div></div><button class="btn g" data-a="editname">${I('edit', 15)}Edit Profile</button></div>${S.editn ? `<div class="card" style="padding:16px;margin-top:12px"><div class="modal" style="padding:0"><label>Full name</label></div><div class="row"><input class="in" id="pname" value="${S.name}"><button class="btn" data-a="savename" style="flex:none">Save</button></div></div>` : ''}
<h3>Appearance</h3><div class="card"><div class="set"><span>Theme</span><span class="chips" style="margin:0">${b('light')}${b('dark')}</span></div></div>
<h3>Account</h3><div class="card"><div class="set"><span>Log out of Taskly on this device</span>${S.conf ? `<span style="display:flex;gap:8px"><button class="btn g" data-a="cancelconf">Cancel</button><button class="btn" data-a="logoutok" style="background:#e5484d">Yes, log out</button></span>` : `<button class="btn g" data-a="logout" style="color:#e5484d">Log Out</button>`}</div></div>`
            }
        };
        function sharedView(h, s, inv) {
            const l = S.tasks.filter(t => t.who !== 'me' || t.share).filter(matches);
            return head(h, s, false) + (inv ? `<div class="card" style="padding:16px;margin-bottom:8px"><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap"><div style="display:flex">${team.map(t => ini(t.id)).join('')}</div><span class="sub" style="flex:1">${team.length} members</span></div><div class="row" style="margin-top:12px"><input class="in" id="inv" placeholder="Invite by email…"><button class="btn" data-a="invite" style="flex:none">Invite</button></div></div>` : '') + `<h3>${l.length} shared tasks</h3>` + (l.map(t => { const own = team.find(m => m.id === t.who) || demoTeam.find(m => m.id === t.who) || team[0]; return `<div class="card task ${t.done ? 'done' : ''}" style="display:block"><div style="display:flex;gap:12px;align-items:flex-start"><button class="cb" data-a="toggle" data-id="${t.id}">${t.done ? I('check', 14, 3) : ''}</button><div style="flex:1"><div class="tt">${t.t}</div><div class="meta">${ini(t.who)}<span>Owner: ${own.n}</span><select class="in" data-a="status" data-id="${t.id}" style="width:auto;padding:2px 8px">${['To do', 'In progress', 'Done'].map(x => `<option ${t.st === x ? 'selected' : ''}>${x}</option>`).join('')}</select><button data-a="cm" data-id="${t.id}" style="color:var(--ac);font-weight:600">${t.cm.length} comments</button></div></div></div>${S.open === t.id ? `<div style="margin:12px 0 0 34px">${t.cm.map(c => `<div class="ds" style="margin-bottom:4px"><b style="color:var(--tx)">Alex:</b> ${c}</div>`).join('')}<input class="in" data-cin="${t.id}" placeholder="Write a comment and press Enter…"></div>` : ''}</div>` }).join('') || empty('No shared tasks yet. Assign one from Add Task.'))
        }
        function modal() {
            const t = S.modal, e = t.id ? S.tasks.find(x => x.id === t.id) : { t: '', d: '', date: t.date || TODAY, time: '09:00', p: 'Medium', c: S.cats[0]?.id, rem: '30 min before', who: 'me' };
            const sel = (id, arr, v) => `<select class="in" id="${id}">${arr.map(([a, b]) => `<option value="${a}" ${a === v ? 'selected' : ''}>${b}</option>`).join('')}</select>`;
            return `<div class="ov" data-a="closem"><div class="card modal"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">${t.id ? 'Edit task' : 'New task'}</h2><button class="ib" data-a="closem">${I('x')}</button></div>
<label>Title *</label><input class="in" id="f-t" value="${e.t}" placeholder="What needs to be done?"><small id="f-e" style="color:#e5484d"></small>
<label>Description</label><textarea class="in" id="f-d" rows="2">${e.d}</textarea>
<div class="row"><div><label>Due date *</label><input class="in" type="date" id="f-date" value="${e.date}"></div><div><label>Due time</label><input class="in" type="time" id="f-time" value="${e.time}"></div></div>
<div class="row"><div><label>Priority</label>${sel('f-p', ['High', 'Medium', 'Low'].map(x => [x, x]), e.p)}</div><div><label>Category</label>${sel('f-c', S.cats.map(c => [c.id, c.n]), e.c)}</div></div>
<div class="row"><div><label>Reminder</label>${sel('f-r', ['None', 'At due time', '30 min before', '1 day before'].map(x => [x, x]), e.rem)}</div><div><label>Assign to</label>${sel('f-w', team.map(m => [m.id, m.n]), e.who)}</div></div>
<div class="row" style="margin-top:20px;justify-content:flex-end"><button class="btn g" data-a="closem" style="flex:none">Cancel</button><button class="btn" data-a="savetask" style="flex:none">Save Task</button></div></div></div>`}
        const act = {
            toggle(id) { const t = S.tasks.find(x => x.id === id); t.done = !t.done; t.doneOn = t.done ? TODAY : null; toast(t.done ? 'Task completed 🎉' : 'Task restored to My Tasks') },
            menu(id) { S.menu = S.menu === id ? null : id }, filter(id) { S.filter = id }, sort(id) { S.sort = id },
            edit(id) { S.menu = null; S.modal = { id } }, add(id) { S.modal = { date: id } }, closem() { S.modal = null },
            del(id) { S.tasks = S.tasks.filter(x => x.id !== id); S.menu = null; toast('Task deleted') },
            savetask() {
                const t = $('#f-t').value.trim(), d = $('#f-date').value; if (!t || !d) { $('#f-t').classList.toggle('err', !t); $('#f-e').textContent = !t ? 'Please enter a title.' : 'Please pick a due date.'; return }
                const v = { t, d: $('#f-d').value, date: d, time: $('#f-time').value || '09:00', p: $('#f-p').value, c: $('#f-c').value, rem: $('#f-r').value, who: $('#f-w').value };
                if (S.modal.id) Object.assign(S.tasks.find(x => x.id === S.modal.id), v); else { S.tasks.unshift({ id: 't' + Date.now(), done: false, doneOn: null, st: 'To do', cm: [], ...v }); S.page = 'tasks'; S.filter = 'all'; S.q = '' }
                toast(S.modal.id ? 'Task updated' : 'Task added ✓'); S.modal = null
            },
            selcat(id) { S.catSel = id }, ren(id) { S.ren = id },
            addcat() { const v = $('#newcat').value.trim(); if (!v) return toast('Enter a category name'); S.cats.push({ id: 'c' + Date.now(), n: v, c: S.cats.length % 6, i: ICONS[S.cats.length % 6] }); toast('Category created') },
            delcat(id) { S.cats = S.cats.filter(c => c.id !== id); if (S.catSel === id) S.catSel = null; toast('Category deleted') },
            calmode(id) { S.cal = id }, calnav(id) { const d = new Date(S.calDate + 'T00:00'); S.cal === 'month' ? d.setMonth(d.getMonth() + +id) : d.setDate(d.getDate() + (S.cal === 'week' ? 7 : 1) * id); S.calDate = iso(d) }, calsel(id) { S.calDate = id },
            read(id) { const m = S.mail.find(x => x.id == id); m.u = 0 },
            notif(id) { S.notif[id] = !S.notif[id] }, privacy() { S.share = !S.share }, ws(id) { S.weekStart = id },
            theme(id) { S.theme = id; toast(id[0].toUpperCase() + id.slice(1) + ' mode on') }, editname() { S.editn = !S.editn }, clearq() { S.q = '' }, demo() { S.tasks = demo.tasks.map(t => ({ ...t, id: 'd' + t.id })); toast('Demo tasks loaded') }, forgot() { toast('Password reset needs the backend email service') }, showpw() { snap(); S.showpw = !S.showpw }, authmode(id) { S.auth = id; S.err = {}; S.f = {}; S.pwv = ''; S.cfv = '' }, logout() { S.conf = true }, cancelconf() { S.conf = false }, logoutmenu() { S.page = 'profile'; S.conf = true }, logoutok() { const pending = saveTimer !== null ? persistNow() : Promise.resolve(); clearTimeout(saveTimer); saveTimer = null; S.user = null; Object.assign(S, { conf: false, auth: 'login', f: {}, err: {}, q: '', tasks: [], mail: [] }); pending.finally(() => api('/api/auth/logout', { method: 'POST' }).catch(() => { })).finally(() => { toast('You have been logged out'); upd() }) },
            savename() { const v = $('#pname').value.trim(); if (v.length < 2) return toast('Enter your full name'); S.name = v; team[0].n = v; S.editn = false; toast('Name updated') },
            async authgo() { snap(); const su = S.auth === 'signup', pw = S.pwv, e = {}; if (su && S.f.name.length < 2) e.name = 'Enter your full name.'; if (!/^\S+@\S+\.\S+$/.test(S.f.email)) e.email = 'Enter a valid email address.'; if (!pw) e.pw = 'Enter a password.'; if (su && S.cfv !== pw) e.cf = 'Passwords do not match.'; S.err = e; if (Object.keys(e).length || S.busy) return; S.busy = true; const remember = su || $('#a-rm')?.checked; upd(); try { const result = await api('/api/auth/' + (su ? 'register' : 'login'), { method: 'POST', body: JSON.stringify({ name: S.f.name, email: S.f.email, password: pw, remember }) }); start(result.user, result.data) } catch (error) { S.err = { [error.field || 'pw']: error.message } } finally { S.busy = false; S.pwv = S.cfv = ''; upd() } },
            async invite() { const email = $('#inv').value.trim(); if (!/.+@.+\..+/.test(email)) return toast('Enter a valid email'); try { const result = await api('/api/invitations', { method: 'POST', body: JSON.stringify({ email }) }); toast(result.message) } catch (error) { toast(error.message) } },
            cm(id) { S.open = S.open === id ? null : id }, go(id) { S.page = id; S.menu = null; window.scrollTo(0, 0) }
        };
        const greet = () => { const h = new Date().getHours(); return (h < 12 ? 'Good morning' : h < 18 ? 'Good afternoon' : 'Good evening') + ', ' + S.name.split(' ')[0] };
        const ini2 = () => S.name.split(' ').map(x => x[0]).join('').slice(0, 2).toUpperCase();
        const firstRun = () => `<div class="card empty" style="padding:56px 24px"><div style="width:64px;height:64px;border-radius:20px;background:var(--acs);color:var(--ac);display:grid;place-items:center;margin:0 auto 14px">${I('done', 30)}</div><h2 style="color:var(--tx);margin:0 0 6px">No tasks yet</h2><p>Add your first task and it will show up here.</p><button class="btn" data-a="add" style="margin:8px auto 0">${I('plus', 16, 2.5)}Add Your First Task</button><div style="margin-top:14px"><button data-a="demo" style="color:var(--ac);font-weight:600">or load optional demo tasks</button></div></div>`;
        const sections = l => {
            const od = l.filter(t => !t.done && t.date < TODAY), today = l.filter(t => t.date === TODAY), future = l.filter(t => !t.done && t.date > TODAY), sec = (h, a, r) => a.length ? `<h3 ${r ? 'style="color:#e5484d"' : ''}>${h} · ${a.length}</h3>` + a.map(c => card(c, c.date !== TODAY)).join('') : '';
            if (S.filter === 'high' || S.filter === 'completed') return sec(S.filter === 'high' ? 'High priority' : 'Completed', l) || empty('No tasks here.');
            return sec('Overdue', od, 1) + sec("Today's Tasks", today) + sec('Upcoming Tasks', future) || empty('Nothing due today. Enjoy the calm!')
        };
        const snap = () => { const g = i => $('#a-' + i)?.value || ''; S.f = { name: g('name').trim(), email: g('email').trim().toLowerCase() }; S.pwv = g('pw'); S.cfv = g('cf') };
        function authView() {
            const su = S.auth === 'signup', e = S.err || {}, f = S.f || {};
            const fld = (id, l, t, ph) => `<label>${l}</label><input class="in ${e[id] ? 'err' : ''}" id="a-${id}" type="${t}" placeholder="${ph}" value="${f[id] || ''}">${e[id] ? `<small style="color:#e5484d">${e[id]}</small>` : ''}`;
            const pwf = (id, l, ph, v, er, eye) => `<label>${l}</label><div style="position:relative"><input class="in ${er ? 'err' : ''}" id="a-${id}" type="${S.showpw ? 'text' : 'password'}" placeholder="${ph}" value="${v || ''}" style="padding-right:42px">${eye ? `<button type="button" class="ib" data-a="showpw" aria-label="Show or hide password" style="position:absolute;right:3px;top:1px">${I('eye')}</button>` : ''}</div>${er ? `<small style="color:#e5484d">${er}</small>` : ''}`;
            return `<div style="min-height:100vh;display:grid;place-items:center;padding:20px"><div class="card modal" style="padding:32px;max-width:420px"><div class="logo" style="justify-content:center;margin-bottom:18px;width:auto"><i>${I('done', 18, 2.5)}</i><span style="display:inline">Taskly</span></div><h1 style="text-align:center;font-size:24px">${su ? 'Create your account' : 'Welcome back'}</h1><p class="sub" style="text-align:center">${su ? 'Start organizing your day in minutes.' : 'Log in to pick up where you left off.'}</p>
${su ? fld('name', 'Full name', 'text', 'Alex Morgan') : ''}${fld('email', 'Email', 'email', 'you@example.com')}${pwf('pw', 'Password', 'Enter your password', S.pwv, e.pw, 1)}${su ? pwf('cf', 'Confirm password', 'Repeat password', S.cfv, e.cf, 0) : `<div class="row" style="align-items:center;margin-top:12px"><label style="display:flex;gap:6px;align-items:center;margin:0;font-weight:500"><input type="checkbox" id="a-rm" checked>Remember me</label><button data-a="forgot" style="color:var(--ac);font-weight:600;text-align:right">Forgot password?</button></div>`}
<button class="btn" data-a="authgo" ${S.busy ? 'disabled' : ''} style="width:100%;justify-content:center;margin-top:18px;opacity:${S.busy ? .6 : 1}">${S.busy ? 'Please wait…' : su ? 'Create account' : 'Log in'}</button>
<p class="sub" style="text-align:center;margin-top:16px">${su ? 'Already have an account?' : 'New to Taskly?'} <button data-a="authmode" data-id="${su ? 'login' : 'signup'}" style="color:var(--ac);font-weight:600">${su ? 'Log in' : 'Create an account'}</button></p><p class="ds" style="text-align:center;font-size:11.5px;margin:8px 0 0">Your account and tasks are stored on the Taskly server.</p></div></div>`
        }
        function render() {
            document.documentElement.dataset.theme = S.theme === 'dark' ? 'dark' : 'light'; if (!S.user) { $('#app').innerHTML = authView(); return }
            const unread = S.mail.filter(m => m.u).length;
            $('#app').innerHTML = `<header><div class="logo"><i>${I('done', 18, 2.5)}</i><span>Taskly</span></div><label class="search">${I('search', 16)}<input id="q" placeholder="Search by title, category or date…" value="${S.q}">${S.q ? `<button class="ib" data-a="clearq" aria-label="Clear search" style="width:26px;height:26px">${I('x', 15)}</button>` : ''}</label><div class="hr" style="position:relative"><button class="ib" data-a="go" data-id="mail" aria-label="Notifications">${I('bell')}${unread ? '<b></b>' : ''}</button><button class="av" data-a="pm" aria-label="Profile menu" style="background:var(--ac);width:34px;height:34px">${ini2()}</button>${S.pm ? `<div class="menu" style="top:46px;right:0;min-width:220px"><div style="padding:8px 10px"><b>${S.name}</b><div class="ds">${S.user}</div></div><button data-a="go" data-id="profile">Profile</button><button data-a="theme" data-id="${S.theme === 'dark' ? 'light' : 'dark'}">Switch to ${S.theme === 'dark' ? 'light' : 'dark'} mode</button><button data-a="logoutmenu" style="color:#e5484d">Log out</button></div>` : ''}</div></header>
<div class="wrap"><aside>${nav.map(x => typeof x === 'string' ? `<h6>${x}</h6>` : `<button class="nv ${S.page === x[0] ? 'on' : ''}" data-a="go" data-id="${x[0]}">${I(x[2])}<span>${x[1]}</span></button>`).join('')}</aside><main>${pages[S.page]()}</main></div>
<nav class="bot">${[['calendar', 'cal'], ['analysis', 'chart']].map(([k, i]) => `<button class="ib ${S.page === k ? 'on' : ''}" data-a="go" data-id="${k}" aria-label="${k}">${I(i, 22)}</button>`).join('')}<button class="plus" data-a="add" aria-label="Add task">${I('plus', 26, 2.5)}</button><button class="ib ${S.page === 'mail' ? 'on' : ''}" data-a="go" data-id="mail" aria-label="Mail">${I('mail', 22)}${unread ? '<b></b>' : ''}</button><button class="ib ${S.page === 'profile' ? 'on' : ''}" data-a="go" data-id="profile" aria-label="Settings" title="Settings">${I('set', 22)}</button></nav>${S.modal ? modal() : ''}`;
            if (S.ren) $('#rn')?.focus();
        }
        const upd = () => { save(); const q = document.activeElement?.id === 'q'; render(); if (q) { const i = $('#q'); i.focus(); i.setSelectionRange(99, 99) } };
        document.addEventListener('click', e => {
            const b = e.target.closest('[data-a]'); if (!b) { if (S.menu || S.pm) { S.menu = null; S.pm = false; upd() } return }
            if (b.tagName === 'SELECT') return; const a = b.dataset.a; if (a === 'closem' && e.target !== b && b.classList.contains('ov') && e.target.closest('.modal')) return;
            if (a !== 'ren' && S.ren && !e.target.closest('#rn')) { const c = S.cats.find(x => x.id === S.ren), v = $('#rn')?.value.trim(); if (c && v) c.n = v; S.ren = null }
            S.pm = a === 'pm' ? !S.pm : false; e.stopPropagation(); act[a]?.(b.dataset.id); upd()
        });
        document.addEventListener('change', e => { if (e.target.dataset.a === 'status') { const t = S.tasks.find(x => x.id === e.target.dataset.id); t.st = e.target.value; if (t.st === 'Done' && !t.done) { t.done = true; t.doneOn = TODAY } toast('Status updated'); upd() } });
        document.addEventListener('input', e => { if (e.target.id === 'q') { S.q = e.target.value; if (S.page !== 'tasks' && !['upcoming', 'completed', 'shared', 'collab'].includes(S.page)) S.page = 'tasks'; upd() } });
        document.addEventListener('keydown', e => {
            if (e.key === 'Enter' && !S.user && e.target.id?.startsWith('a-')) { act.authgo(); upd(); return } if (e.key === 'Enter' && e.target.id === 'rn') { const c = S.cats.find(x => x.id === S.ren); if (e.target.value.trim()) c.n = e.target.value.trim(); S.ren = null; toast('Category renamed'); upd() }
            if (e.key === 'Enter' && e.target.dataset.cin) { const t = S.tasks.find(x => x.id === e.target.dataset.cin); if (e.target.value.trim()) { t.cm.push(e.target.value.trim()); toast('Comment added'); upd() } }
            if (e.key === 'Escape' && S.modal) { S.modal = null; upd() }
        });
        api('/api/auth/me').then(({ user, data }) => enter(user, data)).catch(() => { }).finally(render);
